#ifndef METHODDEFINITION_H
#define METHODDEFINITION_H

#define METHOD_GOMMA 0
#define METHOD_STILO 1
#define METHOD_SELEZIONE 2
#define METHOD_IDGOMMA 3
#define METHOD_TEXT 4

#define GOMMASIZE 5

#endif // METHODDEFINITION_H
