#ifndef SIZEDATA_H
#define SIZEDATA_H

/* definizioni delle strutture per datastruct per il touch */
#define TIPOX double
#define TIPOY TIPOX

#define TIPO_POSIZIONEFOGLIO int
#define TIPO_IDTRATTO TIPO_POSIZIONEFOGLIO
#define TIPO_COLORE TIPO_POSIZIONEFOGLIO*3
#define TIPO_POSIZIONEAUDIO TIPO_POSIZIONEFOGLIO

#define TIPO_PRESSURE float
#define TIPO_ZOOM TIPO_PRESSURE

/* definizioni delle dimensioni per salvabinario */

#define SIZEX sizeof(TIPOX)
#define SIZEY SIZEX

#define SIZEPOSIZIONEFOGLIO sizeof(TIPO_POSIZIONEFOGLIO)
#define SIZEIDTRATTO SIZEPOSIZIONEFOGLIO
#define SIZECOLORE SIZEPOSIZIONEFOGLIO*3
#define SIZEPOSIZIONEAUDIO SIZEPOSIZIONEFOGLIO

#define SIZE_PRESSURE sizeof(TIPO_PRESSURE)
#define SIZE_ZOOM SIZE_PRESSURE

#endif // SIZEDATA_H
