#ifndef SIZEDATA_H
#define SIZEDATA_H

#define SIZEX sizeof(double)
#define SIZEY SIZEX

#define SIZEPOSIZIONEFOGLIO sizeof(int)
#define SIZEIDTRATTO SIZEPOSIZIONEFOGLIO
#define SIZECOLORE SIZEPOSIZIONEFOGLIO*3
#define SIZEPOSIZIONEAUDIO SIZEPOSIZIONEFOGLIO

#define SIZEPRESSURE sizeof(float)
#define SIZEZOOM SIZEPRESSURE

#endif // SIZEDATA_H
